
// FIXME: somehow the generated code erronously passes the javascript code as 
// the first argument!  Need to investigate witx-bindgen-gen-spidermonkey code.
hostcallstr: function(code: string, command: string, payload: string) -> string
